#!/bin/sh
# File generated by ocamlbuild

cd /home/opam/Projektna-Anze.Gartner-1/src

rm -f avtomat.cmi
rm -f avtomat.cmo
rm -f tekstovniVmesnik.cmi
# Also clean the script itself
rm -f /home/opam/Projektna-Anze.Gartner-1/src/_build/sanitize.sh
